export class ficha {
    ans: string = '';
    nomeSolMed: string = '';
    honor: string = ''
    medicInfo: string = '';
    cpf: string = '';
    nCarteira: string = '';
    validadeCart: string = '';
    nomeBen: string = '';
    nomeCol: string = '';
    codOperadora: string = '';
    nomeContradado: string = '';
    cnes: string = '';
    conselhoPro: string = '';
    nConselho: string = '';
    cnpj: string = '';
    dataInternacao: string = '';
    unidAtend: string = '';
    regime: string = '';
    qtdeDiarias: string = '';
    cid: string = '';
    indicacaoClinica: string = '';  
}
